{% set name = "pipx" %}
{% set version = "0.17.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pipx-{{ version }}.tar.gz
  sha256: 3cb13a918491181b317606cd883bcf573435d535d786aa69bc15a76c7f494de2

build:
  number: 0
  noarch: python

  entry_points:
    - pipx = pipx.main:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    # https://github.com/pypa/pipx/blob/main/setup.cfg
    - python >=3.6
    - colorama >=0.4.4
    - userpath >=1.6.0
    - argcomplete >=1.9.4,<2.0
    - packaging >=20.0
    - importlib-metadata >=3.3.0

test:
  imports:
    - pipx
    - pipx.commands
  commands:
    - pip check
    - pipx --help
  requires:
    - pip

about:
  home: https://github.com/pypa/pipx
  summary: Install and Run Python Applications in Isolated Environments
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
