{% set name = "pipx" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pipx-{{ version }}.tar.gz
  sha256: 4d2f70daf15f121e90b7394b0730ee82fc39d7da514e50a7bbf8066be88883bb

build:
  number: 2

  entry_points:
    - pipx = pipx.main:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - hatchling >=0.15.0
  run:
    # https://github.com/pypa/pipx/blob/{{ version }}/pyproject.toml
    - python
    - argcomplete >=1.9.4
    - colorama >=0.4.4  # [win]
    - importlib-metadata >=3.3.0
    - packaging >=20.0
    - userpath >=1.6.0

test:
  imports:
    - pipx
    - pipx.commands
  commands:
    - pip check
    - pipx --help
  requires:
    - pip

about:
  home: https://github.com/pypa/pipx
  summary: Install and Run Python Applications in Isolated Environments
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
